### ISSUE TITLE
Unable to create plugin

### ISSUE THREAD

**Issue by TestFirebaseLogin** [trarbr/vernemq_elixir_plugin#2]
Hi sir,i followed the Readme on the repo for creating elixir plugin, but when i start service after enabling elixir plugin,in logs i see...

2018-04-23 06:45:18.164 [warning] <0.223.0>@vmq_plugin_mgr:check_plugins:409 can't load application plugin vernemq_elixir_plugin due to plugin_not_found
2018-04-23 06:45:18.165 [warning] <0.234.0>@vmq_server_app:start_user_plugin:60 could not start plugin vernemq_elixir_plugin due to plugin_not_found

I have checked multiple times,and path specified is correct.
Any help will be greatly appreciated.

**Comment by larshesel** [comment]
This normally either comes from 1) the path is wrong or 2) the plugin wasn't compiled yet

**Comment by TestFirebaseLogin** [comment]
Thanks a lot sir,now i figured out the problem,actually mine plugin folder was inside the /root folder,and i gave permission to vernemq user on mine folder,so vernemq wasn't able to access the plugin.Once i moved the folder to / and changed path in config file, im able to have the plugin being used by the vernemq.

Also just an advice from you,if im planning to use the mnesia database of mine existing elixir app,which runs on a pod in kubernetes, how can it be done?Should i put code for plugin elixir app in mine app only, or should plugin elixir app be deployed as seperate? 

Thanks for your time.
Cheers!!
