### ISSUE TITLE
auth_on_register hook

### ISSUE THREAD

**Issue by TestFirebaseLogin** [trarbr/vernemq_elixir_plugin#3]
Hi sir,it not actually a bug,but im not able to connect via freenode/#vernemq or slack,https://slack-invite.vernemq.com/...so im opening it as an issue here(Sorry for it,but really need help).

I have implemented elixir plugin, following the repo...but i want to send sustom message on {:error,  :message},but i went through the code https://github.com/erlio/vernemq/blob/a9b666ad042f493fc9cea32c06afac5241b4d0c9/apps/vmq_server/src/vmq_mqtt_fsm.erl on line 539,i realized for any other message than invalid_credentials it sends CONNACK_AUTH.

Any suggestions on how can i send mine custom message to connecting client,so he may know why  he is not authenticated to connect to vernemq broker?

**Comment by trarbr** [comment]
To my knowledge, it is not possible to send custom error messages if authentication fails. The specification for MQTT v3.1.1 lists the possible return codes, as can be seen in section 3.2.2.3 of [the specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html).

I'm not sure if this has been changed in MQTT v5, and I also don't know what VerneMQ's roadmap is for implementing MQTT v5.

**Comment by TestFirebaseLogin** [comment]
So you have any suggestions, or workaround by which i can tell the user reason for which his connection has not been allowed to broker?

**Comment by trarbr** [comment]
One possibility is something like this (rough outline, and feasibility will depend on your use case):

1. Client connects. In your `auth_on_register` callback, you find out they are not allowed. You let them connect anyway, but send a message to some process (let's call it `ConnectionManager`) that this client must be disconnected ASAP.
2. The client connects. It can subscribe to some client-specific topic, like clients/client_id, but all other subscriptions are not allowed (you can modify the list of subscriptions in the `auth_on_subscribe` callback). If the client attempts to publish, you can block that as well with `auth_on_publish`. When the client subscribes to its client-specific topic, you should inform the `ConnectionManager`.
3. Once the client has subscribed to its client-specific topic, the `ConnectionManager` publishes a message on that topic with the error message. Next, the `ConnectionManager` kills the process.

**Comment by TestFirebaseLogin** [comment]
Mine use case is-
I have a authentication setup ,that allows only X active clients,based on ur api key.

Now after checking in database,if limit of devices allowed is exceeded, can i tell the client ,the reason for not allowing connection.(Custom message like number of devices exceeded or api key is invalid)

**Comment by TestFirebaseLogin** [comment]
Thanks for adive sir,i will look int o it,and incase of any doubt i will message on slack
.
